export const QUESTIONS_PER_BATCH = 5

export const QUESTION_BANK = {
  'Senior Frontend Engineer': [
    { id: 'fe1',  text: 'Explain the difference between controlled and uncontrolled components in React.' },
    { id: 'fe2',  text: 'How does the virtual DOM work, and what are its performance implications?' },
    { id: 'fe3',  text: 'Describe your approach to optimising a React app that has slow re-renders.' },
    { id: 'fe4',  text: 'What are React hooks? Explain useCallback vs useMemo with an example.' },
    { id: 'fe5',  text: 'How do you handle global state in large React applications? Compare Redux, Context, and Zustand.' },
    { id: 'fe6',  text: 'Explain CSS specificity and how it affects styling decisions.' },
    { id: 'fe7',  text: 'What is code splitting and how would you implement lazy loading in a React app?' },
    { id: 'fe8',  text: "Walk us through how you'd build an accessible, keyboard-navigable dropdown component." },
    { id: 'fe9',  text: 'How do you approach cross-browser compatibility issues in your CSS?' },
    { id: 'fe10', text: 'Describe the difference between SSR, SSG, and CSR. When would you choose each?' },
    { id: 'fe11', text: 'How would you detect and fix a memory leak in a React application?' },
    { id: 'fe12', text: "Explain the concept of a render prop and when you'd use it over a custom hook." },
    { id: 'fe13', text: 'What strategies do you use to keep bundle size minimal?' },
    { id: 'fe14', text: 'How do you test React components? Describe your testing pyramid.' },
    { id: 'fe15', text: 'Describe a challenging UI bug you fixed and the debugging approach you used.' },
  ],
  'Product Manager': [
    { id: 'pm1',  text: 'How do you prioritise a backlog when there are competing stakeholder demands?' },
    { id: 'pm2',  text: "Walk us through how you'd define success metrics for a new feature." },
    { id: 'pm3',  text: 'Describe a product you launched from 0 to 1. What was your biggest learning?' },
    { id: 'pm4',  text: 'How do you balance user research insights with data-driven decision making?' },
    { id: 'pm5',  text: 'How would you handle a disagreement between engineering and design on a key product decision?' },
    { id: 'pm6',  text: "Explain how you'd run an A/B test. What are common pitfalls to avoid?" },
    { id: 'pm7',  text: 'How do you write a PRD? What sections do you consider non-negotiable?' },
    { id: 'pm8',  text: 'Describe your approach to setting and communicating OKRs to your team.' },
    { id: 'pm9',  text: 'How do you stay updated on industry trends and incorporate them into your roadmap?' },
    { id: 'pm10', text: "Walk us through how you'd diagnose a sudden 20% drop in DAU." },
    { id: 'pm11', text: 'How do you work with engineering to estimate effort without overcomplicating the process?' },
    { id: 'pm12', text: 'Describe a time you killed a feature you personally liked. How did you decide?' },
    { id: 'pm13', text: "How would you build the product roadmap for a B2B SaaS product in its first year?" },
    { id: 'pm14', text: 'What frameworks do you use for competitive analysis?' },
    { id: 'pm15', text: 'How do you gather and synthesise user feedback into actionable product decisions?' },
  ],
  'Data Scientist': [
    { id: 'ds1',  text: 'Explain the bias-variance tradeoff and how it influences model selection.' },
    { id: 'ds2',  text: 'How would you handle class imbalance in a binary classification problem?' },
    { id: 'ds3',  text: 'Walk us through building a recommendation system from scratch.' },
    { id: 'ds4',  text: 'What is overfitting? Describe three techniques to prevent it.' },
    { id: 'ds5',  text: 'Explain the difference between L1 and L2 regularisation.' },
    { id: 'ds6',  text: 'How do you evaluate the performance of a clustering model?' },
    { id: 'ds7',  text: 'Describe a project where you deployed an ML model to production. What challenges did you face?' },
    { id: 'ds8',  text: 'What is feature engineering? Give an example from a real or hypothetical project.' },
    { id: 'ds9',  text: "How would you explain a complex model's predictions to a non-technical stakeholder?" },
    { id: 'ds10', text: 'Compare gradient boosting and random forests. When would you choose one over the other?' },
    { id: 'ds11', text: 'How do you approach missing data in a dataset?' },
    { id: 'ds12', text: 'Explain what attention mechanisms do in transformer models.' },
    { id: 'ds13', text: 'How do you ensure reproducibility in your ML experiments?' },
    { id: 'ds14', text: 'Describe your approach to setting up an ML pipeline for real-time inference.' },
    { id: 'ds15', text: 'What metrics would you use to evaluate an NLP sentiment analysis model?' },
  ],
  'DevOps Engineer': [
    { id: 'dv1',  text: 'Explain the difference between blue-green deployment and canary deployment.' },
    { id: 'dv2',  text: 'How would you design a CI/CD pipeline for a microservices application?' },
    { id: 'dv3',  text: 'Describe how Kubernetes handles pod scheduling and resource allocation.' },
    { id: 'dv4',  text: 'What is infrastructure as code? What tools have you used and why?' },
    { id: 'dv5',  text: 'How do you approach secrets management in a cloud-native environment?' },
    { id: 'dv6',  text: "Explain how you'd set up centralised logging and alerting for a distributed system." },
    { id: 'dv7',  text: 'What is GitOps? Describe a workflow you have implemented using it.' },
    { id: 'dv8',  text: 'How would you reduce the mean time to recovery (MTTR) for production incidents?' },
    { id: 'dv9',  text: 'Describe the difference between horizontal and vertical scaling. When do you choose each?' },
    { id: 'dv10', text: 'How do you ensure zero-downtime deployments in a high-traffic environment?' },
    { id: 'dv11', text: "Walk us through how you'd implement auto-scaling on AWS or GCP." },
    { id: 'dv12', text: 'How do you handle Kubernetes resource limits and requests in production?' },
    { id: 'dv13', text: 'What security hardening steps do you take when provisioning new cloud infrastructure?' },
    { id: 'dv14', text: "Describe how you'd troubleshoot a pod stuck in CrashLoopBackOff." },
    { id: 'dv15', text: 'How do you manage multi-environment (dev/staging/prod) configuration without duplication?' },
  ],
}
