import { useState } from 'react'

const MOCK_JOBS = [
  {
    job_id: 'a6200b2069da48',
    job_code: 'JOB115',
    group_company: 'Scripbox',
    parent_department: 'Engineering',
    department: 'Frontend Engineering',
    division: 'Product',
    business_unit: 'GP_BU_TECH',
    location: ['Bangalore, Karnataka, India'],
    location_city: ['Bangalore'],
    location_country: 'India',
    job_title: 'Senior Frontend Engineer',
    post_on_careers_page: 1,
    post_on_refer_page: 1,
    post_on_ijp_page: 1,
    employee_type: 'Full Time',
    job_created_timestamp: '10-01-2026 10:00:00',
    job_updated_timestamp: '15-03-2026 09:30:00',
    experience_from: '4',
    experience_to: '8',
    is_remote: 0,
    salary_min: '1800000',
    salary_max: '2800000',
  },
  {
    job_id: 'b7311c3170eb59',
    job_code: 'JOB116',
    group_company: 'Scripbox',
    parent_department: 'Product',
    department: 'Product Management',
    division: 'Growth',
    business_unit: 'GP_BU_PROD',
    location: ['Bangalore, Karnataka, India', 'Mumbai, Maharashtra, India'],
    location_city: ['Bangalore', 'Mumbai'],
    location_country: 'India',
    job_title: 'Product Manager – Growth',
    post_on_careers_page: 1,
    post_on_refer_page: 1,
    post_on_ijp_page: 0,
    employee_type: 'Full Time',
    job_created_timestamp: '05-02-2026 11:00:00',
    job_updated_timestamp: '20-03-2026 14:00:00',
    experience_from: '3',
    experience_to: '7',
    is_remote: 0,
    salary_min: '2000000',
    salary_max: '3200000',
  },
  {
    job_id: 'c8422d4281fc60',
    job_code: 'JOB117',
    group_company: 'Scripbox',
    parent_department: 'Data & Analytics',
    department: 'Data Science',
    division: null,
    business_unit: 'GP_BU_DATA',
    location: ['Bangalore, Karnataka, India'],
    location_city: ['Bangalore'],
    location_country: 'India',
    job_title: 'Data Scientist – ML Platform',
    post_on_careers_page: 1,
    post_on_refer_page: 0,
    post_on_ijp_page: 1,
    employee_type: 'Full Time',
    job_created_timestamp: '12-01-2026 09:00:00',
    job_updated_timestamp: '01-03-2026 10:15:00',
    experience_from: '2',
    experience_to: '5',
    is_remote: 1,
    salary_min: '1500000',
    salary_max: '2500000',
  },
  {
    job_id: 'd9533e5392gd71',
    job_code: 'JOB118',
    group_company: 'Scripbox',
    parent_department: 'Infrastructure',
    department: 'DevOps & SRE',
    division: 'Platform',
    business_unit: 'GP_BU_INFRA',
    location: ['Bangalore, Karnataka, India'],
    location_city: ['Bangalore'],
    location_country: 'India',
    job_title: 'DevOps Engineer – Cloud Infrastructure',
    post_on_careers_page: 1,
    post_on_refer_page: 1,
    post_on_ijp_page: 1,
    employee_type: 'Full Time',
    job_created_timestamp: '20-02-2026 08:30:00',
    job_updated_timestamp: '22-03-2026 11:00:00',
    experience_from: '3',
    experience_to: '6',
    is_remote: 0,
    salary_min: '1600000',
    salary_max: '2400000',
  },
  {
    job_id: 'e0644f6403he82',
    job_code: 'JOB119',
    group_company: 'Scripbox',
    parent_department: 'Engineering',
    department: 'Backend Engineering',
    division: 'Core Platform',
    business_unit: 'GP_BU_TECH',
    location: ['Remote'],
    location_city: ['Remote'],
    location_country: 'India',
    job_title: 'Backend Engineer – Node.js',
    post_on_careers_page: 1,
    post_on_refer_page: 1,
    post_on_ijp_page: 0,
    employee_type: 'Full Time',
    job_created_timestamp: '01-03-2026 12:00:00',
    job_updated_timestamp: '25-03-2026 16:00:00',
    experience_from: '3',
    experience_to: '7',
    is_remote: 1,
    salary_min: '1700000',
    salary_max: '2600000',
  },
  {
    job_id: 'f1755g7514if93',
    job_code: 'JOB120',
    group_company: 'Scripbox',
    parent_department: 'Design',
    department: 'UX & Design',
    division: null,
    business_unit: 'GP_BU_DESIGN',
    location: ['Bangalore, Karnataka, India'],
    location_city: ['Bangalore'],
    location_country: 'India',
    job_title: 'UX Designer – Mobile',
    post_on_careers_page: 1,
    post_on_refer_page: 0,
    post_on_ijp_page: 0,
    employee_type: 'Contract',
    job_created_timestamp: '15-03-2026 10:00:00',
    job_updated_timestamp: '26-03-2026 09:00:00',
    experience_from: '2',
    experience_to: '5',
    is_remote: 0,
    salary_min: '1200000',
    salary_max: '2000000',
  },
  {
    job_id: 'g2866h8625jg04',
    job_code: 'JOB121',
    group_company: 'Scripbox',
    parent_department: 'Engineering',
    department: 'Mobile Engineering',
    division: 'Consumer Apps',
    business_unit: 'GP_BU_MOBILE',
    location: ['Bangalore, Karnataka, India', 'Hyderabad, Telangana, India'],
    location_city: ['Bangalore', 'Hyderabad'],
    location_country: 'India',
    job_title: 'React Native Engineer',
    post_on_careers_page: 1,
    post_on_refer_page: 1,
    post_on_ijp_page: 1,
    employee_type: 'Full Time',
    job_created_timestamp: '18-02-2026 14:00:00',
    job_updated_timestamp: '24-03-2026 13:30:00',
    experience_from: '3',
    experience_to: '6',
    is_remote: 0,
    salary_min: '1600000',
    salary_max: '2500000',
  },
  {
    job_id: 'h3977i9736kh15',
    job_code: 'JOB122',
    group_company: 'Scripbox',
    parent_department: 'Finance',
    department: 'Finance & Accounting',
    division: null,
    business_unit: 'GP_BU_FIN',
    location: ['Bangalore, Karnataka, India'],
    location_city: ['Bangalore'],
    location_country: 'India',
    job_title: 'Finance Analyst',
    post_on_careers_page: 0,
    post_on_refer_page: 0,
    post_on_ijp_page: 1,
    employee_type: 'Full Time',
    job_created_timestamp: '22-03-2026 09:00:00',
    job_updated_timestamp: '26-03-2026 10:00:00',
    experience_from: '1',
    experience_to: '3',
    is_remote: 0,
    salary_min: '800000',
    salary_max: '1400000',
  },
]

export function useJobs() {
  const [jobs]    = useState(MOCK_JOBS)
  const [loading] = useState(false)
  const [error]   = useState(null)

  return { jobs, loading, error, refetch: () => {} }
}
